### PR TITLE
Fix ParameterInformation

### PR DESCRIPTION
**Pull request by r3m0t**
Fix for jedi-language-server

### CODE REVIEW

**Comment by karthiknadig** [comment]
@r3m0t can you run `python -m nox format` that should address all formatting and linting issues.

**Comment by r3m0t** [comment]
Done `python -m nox -s format`, it changed a lot of other files as well but I didn't commit those changes. Odd.

**Review by karthiknadig — DISMISSED** [review]

**Comment by karthiknadig** [comment]
Looks like docformatter has made minor changes to how it formats things. I will push an update to this PR.

**Comment by r3m0t** [comment]
Ah, Python, where three lockfiles are still not enough 🤣

**Review by karthiknadig — APPROVED** [review]

**Comment by brettcannon** [comment]
> Ah, Python, where three lockfiles are still not enough 🤣

I'm working on it. 😉

**Pull request merged**
