### PR TITLE
Add structure hook for `Union[str, List[InlayHintLabelPart]]`

### LINKED ISSUE #218: Missing structure hook for `InlayHint`
```python
Unable to deserialize message
  + Exception Group Traceback (most recent call last):
  |   File "/var/home/alex/Projects/pygls/pygls/protocol.py", line 405, in _deserialize_message
  |     return self._converter.structure(data, request_type)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/var/home/alex/Projects/pygls/.env/lib64/python3.11/site-packages/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure lsprotocol.types.InlayHintResolveRequest>", line 26, in structure_InlayHintResolveRequest
  |     if errors: raise __c_cve('While structuring ' + 'InlayHintResolveRequest', errors, __cl)
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring InlayHintResolveRequest (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure lsprotocol.types.InlayHintResolveRequest>", line 10, in structure_InlayHintResolveRequest
    |     res['params'] = __c_structure_params(o['params'], __c_type_params)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure lsprotocol.types.InlayHint>", line 50, in structure_InlayHint
    |     if errors: raise __c_cve('While structuring ' + 'InlayHint', errors, __cl)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring InlayHint (1 sub-exception)
    | Structuring class InlayHintResolveRequest @ attribute params
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "<cattrs generated structure lsprotocol.types.InlayHint>", line 10, in structure_InlayHint
      |     res['label'] = __c_structure_label(o['label'], __c_type_label)
      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/var/home/alex/Projects/pygls/.env/lib64/python3.11/site-packages/cattrs/converters.py", line 377, in _structure_error
      |     raise StructureHandlerNotFoundError(msg, type_=cl)
      | cattrs.errors.StructureHandlerNotFoundError: Unsupported type: typing.Union[str, typing.List[lsprotocol.types.InlayHintLabelPart]]. Register a structure hook for it.
      | Structuring class InlayHint @ attribute label
      +------------------------------------
```

### PR DESCRIPTION
**Pull request by alcarney**
Fixes #218

### CODE REVIEW

**Review by karthiknadig — DISMISSED** [review]

**Comment by karthiknadig** [comment]
@alcarney It looks like how pygls used to run tests has changed. Would it be possible for you to update the github workflow so that we can run pygls tests as smoke tests?

**Comment by alcarney** [comment]
It is not immediately obvious to me why the test suite would hang before running any tests - especially when they seem to run fine over on the pygls repo....

But I will have a look and see if I can reproduce it locally

**Comment by karthiknadig** [comment]
@alcarney I was running `pytest` directly, but it looks like we should probably use `tox` to run `pygls` tests.

**Comment by alcarney** [comment]
@karthiknadig I reproduced it locally  - test suite hangs on the second test.
I seem to remember having issues with that test when I wrote it originally - hopefully I can remember what the issue was!
```
================================================= test session starts =================================================
platform linux -- Python 3.11.3, pytest-7.3.2, pluggy-1.0.0
rootdir: /var/home/alex/Projects/lsprotocol/smoke_tests
configfile: pyproject.toml
plugins: typeguard-4.0.0, asyncio-0.21.0
asyncio: mode=Mode.AUTO
collected 213 items                                                                                                   

smoke_tests/tests/test_client.py::test_client_detect_server_exit 
--------------------------------------------------- live log setup ----------------------------------------------------
DEBUG    asyncio:selector_events.py:54 Using selector: EpollSelector
DEBUG    asyncio:selector_events.py:54 Using selector: EpollSelector
---------------------------------------------------- live log call ----------------------------------------------------
DEBUG    pygls.client:client.py:110 Starting server process: /var/home/alex/Projects/lsprotocol/.ci/bin/python -c print('Hello, World!')
DEBUG    pygls.client:client.py:134 Server process 105533 exited with return code: 0
PASSED                                                                                                          [  0%]
-------------------------------------------------- live log teardown --------------------------------------------------
DEBUG    asyncio:selector_events.py:54 Using selector: EpollSelector

smoke_tests/tests/test_client.py::test_client_detect_invalid_json 
--------------------------------------------------- live log setup ----------------------------------------------------
DEBUG    asyncio:selector_events.py:54 Using selector: EpollSelector
---------------------------------------------------- live log call ----------------------------------------------------
DEBUG    pygls.client:client.py:110 Starting server process: /var/home/alex/Projects/lsprotocol/.ci/bin/python /var/home/alex/Projects/lsprotocol/smoke_tests/tests/servers/invalid_json.py
DEBUG    pygls.protocol:protocol.py:583 Sending request with id "e7f074c7-fca1-485e-881a-9b94dde57a17": method/name {}
INFO     pygls.protocol:protocol.py:462 Sending data: {"id": "e7f074c7-fca1-485e-881a-9b94dde57a17", "method": "method/name", "jsonrpc": "2.0", "params": {}}
DEBUG    pygls.client:client.py:134 Server process 105539 exited with return code: 1

```

**Review by eleanorjboyd — APPROVED** [review]

**Pull request merged**
