### PR TITLE
Use Sequence instead of List

### PR DESCRIPTION
**Pull request by muffinmad**
```
pip install lsprotocol
pip install mypy
```

The `main.py`:
```
from typing import List
from lsprotocol import types


def get_edits() -> List[types.TextEdit]:
    return [
        types.TextEdit(
            types.Range(types.Position(0, 0), types.Position(0, 1)),
            'new text'
        )
    ]


edits = get_edits()

types.TextDocumentEdit(
    types.OptionalVersionedTextDocumentIdentifier('file', 1),
    edits,
)
```

The output of `mypy main.py`:
```
main.py:18: error: Argument 2 to "TextDocumentEdit" has incompatible type "list[TextEdit]"; expected "list[TextEdit | AnnotatedTextEdit]"  [arg-type]
main.py:18: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
main.py:18: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

Replacing `List` with `Sequence` solve the error reported by Mypy:
```
Success: no issues found in 1 source file
```

### CODE REVIEW

**Comment by karthiknadig** [comment]
@muffinmad Can you also run the generator? you can run this from project root.
```
python -m generator --plugin python
```

**Comment by muffinmad** [comment]
@karthiknadig Sure. But is it ok that running generator introduces so many changes to `types.py`? E.g.
```
-Definition = Union["Location", List["Location"]]
+Definition = Union['Location',Sequence['Location']]
```
Not only `List` replaced by `Sequence` but quotes style also changed as well as space after `,` disappeared.

**Comment by karthiknadig** [comment]
Install `nox` into your environment, then run `nox --session format`. That should fix everything.

**Comment by muffinmad** [comment]
@microsoft-github-policy-service agree

**Review by karthiknadig — DISMISSED** [review]

**Comment by karthiknadig** [comment]
You might need to update `_hook.py` where a lot of the things are registered as `List`.

**Review by Tyriar — APPROVED** [review]

**Review by karthiknadig — APPROVED** [review]

**Review by karrtikr — APPROVED** [review]

**Pull request merged**
